package vistas;

import controlador.conexionMysql;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Clientes;
import sun.util.logging.PlatformLogger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Velasquez
 */
public class IngresarCliente  extends javax.swing.JInternalFrame {

  //  public static Connection connection;
    public IngresarCliente() {
        initComponents();   // metodo para que abra el jfram 
    }
    
    
     
     public void limpiarCajas(){//METODO PARA LIMPIAR LAS CAJAS
     
         caja6Direccion.setText("");
         caja2Nombre.setText("");
         caja3Apellido.setText("");
         caja4Telefono.setText("");
         caja5Correo.setText("");
         caja1Cedula.setText("");
         
     
     }
     public int ClienteExistente(String Id) // metotod que permite validar si el id ya exixte en la BD para la insercion
    {
    int esta=0;
    
     String comandosql="Select * from clientes where id_cliente= "+ Id;
     Statement sentencia;
     ResultSet resultado;// GUARDA EL RESULTADO DE LA CONSULTA
     
         conexionMysql ConectBD1=new conexionMysql();// se crea un objeto de la clase conexionMysql
         ConectBD1.iniciarConexion();// el objeto inicia la conexion y se hace el llamado al metodo que se creo en el controlador
         Connection conn1=ConectBD1.getMyConnection();
        try {
            sentencia= conn1.createStatement();
            resultado = sentencia.executeQuery(comandosql);
          //  ResultSetMetaData meta = resultado.getMetaData();
             while (resultado.next()) 
            { 
                esta=1;
                JOptionPane.showMessageDialog(null, "El Id ya existe " +Id);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IngresarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
         ConectBD1.Cerrar();
        return esta;
    
    }
   
      
    
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        caja1Cedula = new javax.swing.JTextField();
        caja5Correo = new javax.swing.JTextField();
        Caja7Genero = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        caja3Apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Caja8Estado = new javax.swing.JLabel();
        btncrearCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        caja6Direccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        caja2Nombre = new javax.swing.JTextField();
        caja4Telefono = new javax.swing.JTextField();
        jComboGenero = new javax.swing.JComboBox<>();
        jComboEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REGISTRAR CLIENTES");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login.png"))); // NOI18N

        jLabel3.setText("TELEFONO");

        jLabel4.setText("EIMAIL");

        caja1Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja1CedulaActionPerformed(evt);
            }
        });
        caja1Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja1CedulaKeyTyped(evt);
            }
        });

        caja5Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja5CorreoKeyTyped(evt);
            }
        });

        Caja7Genero.setText("GENERO");

        jLabel7.setText("APELLIDO");

        caja3Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja3ApellidoActionPerformed(evt);
            }
        });
        caja3Apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja3ApellidoKeyTyped(evt);
            }
        });

        jLabel5.setText("DIRECCION");

        Caja8Estado.setText("ESTADO");

        btncrearCliente.setText("CREAR CLIENTE");
        btncrearCliente.setToolTipText("REGISTRARÁ EL CLIENTE");
        btncrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE");

        caja6Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja6DireccionKeyTyped(evt);
            }
        });

        jLabel2.setText("CEDULA");

        caja2Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja2NombreActionPerformed(evt);
            }
        });
        caja2Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja2NombreKeyTyped(evt);
            }
        });

        caja4Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja4TelefonoKeyTyped(evt);
            }
        });

        jComboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jComboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGeneroActionPerformed(evt);
            }
        });

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(Caja8Estado)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Caja7Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caja4Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja5Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja1Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja3Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja6Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btncrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caja1Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(caja3Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja4Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja5Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja6Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caja7Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caja8Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btncrearCliente)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caja1CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja1CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja1CedulaActionPerformed

    private void caja3ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja3ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja3ApellidoActionPerformed

    
    private void btncrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearClienteActionPerformed
        int a;
       a=ClienteExistente(caja1Cedula.getText());
       if (a==0){
        try{
            
            String c="";
            if(caja1Cedula.getText().isEmpty()){  //codigo que permite validar que ningun campo este vacio 
                c=c+"No. cedula \n";
            }
            
            if(caja2Nombre.getText().isEmpty()){
                c=c+"No. nombre \n";
            }
            if(caja3Apellido.getText().isEmpty()){
                c=c+"  apellido";
            }
            if(caja4Telefono.getText().isEmpty()){
                c=c+"  telefono";
            }
            if(caja5Correo.getText().isEmpty()){
                c=c+"  Correo";
            }
            if(caja6Direccion.getText().isEmpty()){
                c=c+"  direccion";
            }
            if(caja1Cedula.getText().isEmpty() || caja2Nombre.getText().isEmpty() || caja3Apellido.getText().isEmpty() || caja4Telefono.getText().isEmpty() ||
               caja5Correo.getText().isEmpty() || caja6Direccion.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Faltó ingresar información en los siguientes campos: "+c+".","Falta de información",JOptionPane.CANCEL_OPTION);
            limpiarCajas();
            }else{
                
            conexionMysql ConectBD=new conexionMysql();// se crea un objeto de la clase conexionMysql
            ConectBD.iniciarConexion();// el objeto inicia la conexion y se hace el llamado al metodo que se creo en el controlador
            Connection conn=ConectBD.getMyConnection();// se crea una variable de
            CallableStatement sentenciaCargada = conn.prepareCall("{call INGRESAR_CLIENTE(?,?,?,?,?,?,?,?)}");
            sentenciaCargada.setString(1,caja1Cedula.getText()); // .registerOutParameter(CajitaIdpaciente.getText(), java.sql.Types.VARCHAR);
            sentenciaCargada.setString(2,caja2Nombre.getText());
            sentenciaCargada.setString(3,caja3Apellido.getText());
            sentenciaCargada.setString(4,caja4Telefono.getText());
            sentenciaCargada.setString(5,caja5Correo.getText());
            sentenciaCargada.setString(6,caja6Direccion.getText());
            sentenciaCargada.setString(7,jComboGenero.getSelectedItem().toString());
            sentenciaCargada.setString(8,jComboEstado.getSelectedItem().toString());
            sentenciaCargada.execute();
            JOptionPane.showMessageDialog(null,"Cliente "+ caja2Nombre.getText() +" fue almacenado");
            ConectBD.Cerrar();
            limpiarCajas();
            }
        }
          catch (SQLException ex) {
          Logger.getLogger(IngresarCliente.class.getName()).log(Level.SEVERE, null, ex);// nombre de la clase
         }
        }
    }//GEN-LAST:event_btncrearClienteActionPerformed

    
    
    
    private void caja2NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja2NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja2NombreActionPerformed

    private void jComboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGeneroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboGeneroActionPerformed

    private void caja6DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja6DireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_caja6DireccionKeyTyped

    private void caja2NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja2NombreKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if (Character.isDigit(num)) { // codigo que permite el ingreso de solo TEXTO 
           evt.consume();
        } 
    }//GEN-LAST:event_caja2NombreKeyTyped

    private void caja3ApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja3ApellidoKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if (Character.isDigit(num)) { // codigo que permite el ingreso de solo TEXTO 
           evt.consume();
        }
    }//GEN-LAST:event_caja3ApellidoKeyTyped

    private void caja4TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja4TelefonoKeyTyped
        // TODO add your handling code here:
         int num = evt.getKeyChar();
        if (Character.isAlphabetic(num)) { // codigo que permite el ingreso de solo NUMEROS
           evt.consume();
        }
    }//GEN-LAST:event_caja4TelefonoKeyTyped

    private void caja5CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja5CorreoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_caja5CorreoKeyTyped

    private void caja1CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja1CedulaKeyTyped
        // TODO add your handling code here:
         int num = evt.getKeyChar();
        if (Character.isAlphabetic(num)) { // codigo que permite el ingreso de solo NUMEROS
           evt.consume();
        }
    }//GEN-LAST:event_caja1CedulaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caja7Genero;
    private javax.swing.JLabel Caja8Estado;
    private javax.swing.JButton btncrearCliente;
    private javax.swing.JTextField caja1Cedula;
    private javax.swing.JTextField caja2Nombre;
    private javax.swing.JTextField caja3Apellido;
    private javax.swing.JTextField caja4Telefono;
    private javax.swing.JTextField caja5Correo;
    private javax.swing.JTextField caja6Direccion;
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JComboBox<String> jComboGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
