package vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Velasquez
 */
public class principal extends javax.swing.JFrame {

    IngresarCliente objIngresarCliente;  // validando las ventanas 
    MostrarClientes objMostrarClientes;
    RegistrarPedidos objRegistrarPed;
    ActualizarServicios objActualizarServ;
    InsertarServiciosProced objInsertarServ;
    InsertarMedidasSuperiores objInsertMedidasSuperiores;
    InsertarMedidasInferiores objInsertMedidasInferiores;
    ActualizarYmostrarSup objActuaYmostrarSup;
    ActualizarYmostrarInf objActuaYmostrarInf;
    MostrarActualizarPedidos objMostrarActuPedido; 
    
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        escritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton9 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton10 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton11 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton12 = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItenRegistrarCliente = new javax.swing.JMenuItem();
        ItemMostrarClientes = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        InsertSup = new javax.swing.JMenuItem();
        InsertInf = new javax.swing.JMenuItem();
        UpdateSup = new javax.swing.JMenuItem();
        UpdateInf = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        InsertarServ = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("File");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar1.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("S.A.T.C.O");

        escritorio.setName(""); // NOI18N

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/login.png"))); // NOI18N
        jButton1.setToolTipText("Registrar Cliente");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator14);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/refresh.png"))); // NOI18N
        jButton2.setToolTipText("Mostrar y Actualizar Clientes");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator13);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/shirt.png"))); // NOI18N
        jButton3.setToolTipText("Medidas Superiores");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator12);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/jeans.png"))); // NOI18N
        jButton4.setToolTipText("Medidas Inferiores");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator11);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotation.png"))); // NOI18N
        jButton5.setToolTipText("Actualizar Medidas Superiores");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator10);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rotate.png"))); // NOI18N
        jButton6.setToolTipText("Actualizar Medidas Inferiores");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);
        jToolBar1.add(jSeparator9);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/order.png"))); // NOI18N
        jButton7.setToolTipText("Registrar Pedido");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator4);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/choices.png"))); // NOI18N
        jButton8.setToolTipText("Mostrar y Actualizar Pedidos");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton8);
        jToolBar1.add(jSeparator8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/shopping-bag.png"))); // NOI18N
        jButton9.setToolTipText("Registrar Ventas");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton9);
        jToolBar1.add(jSeparator3);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/choices.png"))); // NOI18N
        jButton10.setToolTipText("Filtrar Ventas");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton10);
        jToolBar1.add(jSeparator2);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/spool-of-thread.png"))); // NOI18N
        jButton11.setToolTipText("Ingresar Servicios");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton11);
        jToolBar1.add(jSeparator1);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/funnel.png"))); // NOI18N
        jButton12.setToolTipText("Actualizar Servicios");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton12);
        jToolBar1.add(jSeparator15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/KK.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        escritorio.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 276, Short.MAX_VALUE))
        );

        jMenu1.setText("Clientes");

        ItenRegistrarCliente.setText("Registrar Cliente");
        ItenRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItenRegistrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(ItenRegistrarCliente);

        ItemMostrarClientes.setText("Mostrar y Actualizar");
        ItemMostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMostrarClientesActionPerformed(evt);
            }
        });
        jMenu1.add(ItemMostrarClientes);

        menu.add(jMenu1);

        jMenu7.setText("Medidas");

        InsertSup.setText("Insertar Medidas Superiores");
        InsertSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertSupActionPerformed(evt);
            }
        });
        jMenu7.add(InsertSup);

        InsertInf.setText("Insertar Medidas Inferiores");
        InsertInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertInfActionPerformed(evt);
            }
        });
        jMenu7.add(InsertInf);

        UpdateSup.setText("Mostrar y Actualizar Medidas Superiores");
        UpdateSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSupActionPerformed(evt);
            }
        });
        jMenu7.add(UpdateSup);

        UpdateInf.setText("Mostrar y Actualizar Medidas Inferiores");
        UpdateInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfActionPerformed(evt);
            }
        });
        jMenu7.add(UpdateInf);

        menu.add(jMenu7);

        jMenu2.setText("Pedidos");

        jMenuItem4.setText("Registrar Pedido");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem12.setText("Mostrar y Actualizar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        menu.add(jMenu2);

        jMenu3.setText("Ventas");

        jMenuItem14.setText("Registrar Ventas");
        jMenu3.add(jMenuItem14);

        jMenuItem15.setText("Filtrar Ventas");
        jMenu3.add(jMenuItem15);

        menu.add(jMenu3);

        jMenu6.setText("Servicios");

        InsertarServ.setText("Ingresar Servicios");
        InsertarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarServActionPerformed(evt);
            }
        });
        jMenu6.add(InsertarServ);

        jMenuItem7.setText("Actualizar Servicios");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        menu.add(jMenu6);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItenRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItenRegistrarClienteActionPerformed
        // TODO add your handling code here:
         if(objIngresarCliente==null || objIngresarCliente.isClosed())// condicional
        {
             try{
             
                objIngresarCliente=new IngresarCliente();// intanciar clase
                }catch (Exception ex) {
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                 
             }
                escritorio.add(objIngresarCliente); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objIngresarCliente.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_ItenRegistrarClienteActionPerformed

    private void InsertarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarServActionPerformed
        // TODO add your handling code here:kkk
          if(objInsertarServ==null || objInsertarServ.isClosed())// condicional
        {
             try{
             
                objInsertarServ=new  InsertarServiciosProced();// intanciar clase
                }catch(SQLException ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                 
             }
                escritorio.add( objInsertarServ); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objInsertarServ.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_InsertarServActionPerformed

    private void ItemMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMostrarClientesActionPerformed
        // TODO add your handling code here:
          if(objMostrarClientes==null || objMostrarClientes.isClosed())// condicional
        {
             try{
             
                  objMostrarClientes=new  MostrarClientes();// intanciar clase
                }catch(SQLException ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                 
             }
                 escritorio.add( objMostrarClientes); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                  objMostrarClientes.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_ItemMostrarClientesActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
          if(objMostrarActuPedido==null || objMostrarActuPedido.isClosed())// condicional
        {
             try{
             
                objMostrarActuPedido=new  MostrarActualizarPedidos();// intanciar clase
                }catch(Exception ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                 
             }
                escritorio.add( objMostrarActuPedido); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objMostrarActuPedido.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if(objInsertarServ==null || objInsertarServ.isClosed())// condicional
        {
             try{
                objInsertarServ=new  InsertarServiciosProced();// intanciar clase
                }catch(Exception ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                }
                escritorio.add( objInsertarServ); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objInsertarServ.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:ooooo
        if(objActualizarServ==null || objActualizarServ.isClosed())// condicional
        {
             try{
                objActualizarServ=new ActualizarServicios();// intanciar clase
                }catch(SQLException ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                }
                escritorio.add( objActualizarServ); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objActualizarServ.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void InsertInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertInfActionPerformed
        // TODO add your handling code here:
         if(objInsertMedidasInferiores==null || objInsertMedidasInferiores.isClosed())// condicional
        {
             try{
                objInsertMedidasInferiores=new InsertarMedidasInferiores();// intanciar clase
                }catch(Exception ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                }
                escritorio.add( objInsertMedidasInferiores); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objInsertMedidasInferiores.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_InsertInfActionPerformed

    private void InsertSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertSupActionPerformed
        // TODO add your handling code here:sup
        if(objInsertMedidasSuperiores==null || objInsertMedidasSuperiores.isClosed())// condicional
        {
             try{
                objInsertMedidasSuperiores=new InsertarMedidasSuperiores();// intanciar clase
                }catch(Exception ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                }
                escritorio.add( objInsertMedidasSuperiores); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objInsertMedidasSuperiores.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_InsertSupActionPerformed

    private void UpdateInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfActionPerformed
        // TODO add your handling code here: objInsertMedidasInferiores
        if(objActuaYmostrarInf==null || objActuaYmostrarInf.isClosed())// condicional
        {
             try{
                objActuaYmostrarInf=new ActualizarYmostrarInf();// intanciar clase
                }catch(Exception ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                }
                escritorio.add( objActuaYmostrarInf); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objActuaYmostrarInf.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_UpdateInfActionPerformed

    private void UpdateSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSupActionPerformed
        // TODO add your handling code here:
        if(objActuaYmostrarSup==null || objActuaYmostrarSup.isClosed())// condicional
        {
             try{
                objActuaYmostrarSup=new ActualizarYmostrarSup();// intanciar clase
                }catch(Exception ex){
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE,null,ex);
                }
                escritorio.add( objActuaYmostrarSup); // escritorio es el fondo de la ventana PRINCIPAL Y se llama al objeto 
                objActuaYmostrarSup.show();// mostrar la ventana de la clase ingresarcliente
        
        }
    }//GEN-LAST:event_UpdateSupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InsertInf;
    private javax.swing.JMenuItem InsertSup;
    private javax.swing.JMenuItem InsertarServ;
    private javax.swing.JMenuItem ItemMostrarClientes;
    private javax.swing.JMenuItem ItenRegistrarCliente;
    private javax.swing.JMenuItem UpdateInf;
    private javax.swing.JMenuItem UpdateSup;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
